/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo.tugas.tiga;

import java.awt.Color;

/**
 *
 * @author septianpadli
 */
public class InputForm extends javax.swing.JFrame {

    /**
     * Creates new form InputForm
     */
    public InputForm() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LabelUsia = new javax.swing.JLabel();
        LabelBB = new javax.swing.JLabel();
        LabelJK = new javax.swing.JLabel();
        LabelAktivitas = new javax.swing.JLabel();
        InputUsia = new javax.swing.JTextField();
        InputBB = new javax.swing.JTextField();
        InputJK = new javax.swing.JComboBox<>();
        InputAktivitas = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        ButtonHitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Hitung Gizi Harianmu");

        LabelUsia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelUsia.setText("Usia");

        LabelBB.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelBB.setText("Berat Badan");

        LabelJK.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelJK.setText("Jenis Kelamin");

        LabelAktivitas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelAktivitas.setText("Tingkat Aktivitas");

        InputUsia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        InputUsia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 3, 3), 1, true));
        InputUsia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputUsiaActionPerformed(evt);
            }
        });

        InputBB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        InputBB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 3, 3), 1, true));
        InputBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputBBActionPerformed(evt);
            }
        });

        InputJK.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        InputJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "laki-laki", "perempuan" }));
        InputJK.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 3, 3), 1, true));

        InputAktivitas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        InputAktivitas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tidak aktif", "ringan", "sedang", "berat" }));
        InputAktivitas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 3, 3), 1, true));

        ButtonHitung.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonHitung.setText("Hitung");
        ButtonHitung.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 3, 3), 1, true));
        ButtonHitung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonHitungMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelJK)
                    .addComponent(LabelUsia)
                    .addComponent(LabelBB)
                    .addComponent(LabelAktivitas))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InputBB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(InputUsia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(InputJK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(InputAktivitas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 160, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputUsia, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(LabelUsia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputBB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelBB))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputJK, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(LabelJK))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelAktivitas)
                            .addComponent(InputAktivitas, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(ButtonHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(83, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputUsiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputUsiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputUsiaActionPerformed

    private void InputBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputBBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputBBActionPerformed

    private void ButtonHitungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonHitungMouseClicked
        // TODO add your handling code here:
        try {
            int usia = Integer.parseInt(InputUsia.getText());
            int berat = Integer.parseInt(InputBB.getText());
            String gender = (String) InputJK.getSelectedItem();
            String aktivitas = (String) InputAktivitas.getSelectedItem();
            
            double proteinMinimal, proteinMaksimal;
            int karboMinimal, karboMaksimal, serat;
            
//            hitung serat
            if (usia <= 3) {
                serat = 19;
            } else if(usia <= 8) {
                serat = 25;
            } else if (usia <= 13) {
                if ("perempuan".equalsIgnoreCase(gender)) {
                    serat = 26;
                } else {
                    serat = 31;
                }
            } else if (usia <= 18) {
                if ("perempuan".equalsIgnoreCase(gender)) {
                    serat = 26;
                } else {
                    serat = 38;
                }
            } else if (usia <= 50) {
                if ("perempuan".equalsIgnoreCase(gender)) {
                    serat = 25;
                } else {
                    serat = 38;
                }
            } else if (usia > 50) {
                if ("perempuan".equalsIgnoreCase(gender)) {
                    serat = 21;
                } else {
                    serat = 30;
                }
            } else {
                throw new NumberFormatException("Nilai usia tidak valid.");
            }
            
//            hitung protein
            if (aktivitas.equalsIgnoreCase("tidak aktif")) {
                proteinMinimal = 0.8 * berat;
                proteinMaksimal = 1.0 * berat;
            } else if (aktivitas.equalsIgnoreCase("ringan") || aktivitas.equalsIgnoreCase("sedang")) {
                proteinMinimal = 1.2 * berat;
                proteinMaksimal = 1.6 * berat;
            } else if (aktivitas.equalsIgnoreCase("berat")) {
                proteinMinimal = 1.6 * berat;
                proteinMaksimal = 2.2 * berat;
            } else {
                throw new NumberFormatException("Aktivias tidak valid.");
            }
            
//            hitung karbo
            if (aktivitas.equalsIgnoreCase("tidak aktif")) {
                karboMinimal = 2 * berat;
                karboMaksimal = 3 * berat;
            } else if (aktivitas.equalsIgnoreCase("ringan")) {
                karboMinimal = 3 * berat;
                karboMaksimal = 5 * berat;
            } else if (aktivitas.equalsIgnoreCase("sedang")) {
                karboMinimal = 5 * berat;
                karboMaksimal = 7 * berat;
            } else if (aktivitas.equalsIgnoreCase("berat") || aktivitas.equalsIgnoreCase("atlet")) {
                karboMinimal = 6 * berat;
                karboMaksimal = 10 * berat;
            } else {
                throw new NumberFormatException("Aktivitas tidak valid.");
            }

            OutputFrame output = new OutputFrame(usia, berat, gender, aktivitas, proteinMinimal, proteinMaksimal, karboMinimal, karboMaksimal, serat);
            output.setVisible(true);
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_ButtonHitungMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonHitung;
    private javax.swing.JComboBox<String> InputAktivitas;
    private javax.swing.JTextField InputBB;
    private javax.swing.JComboBox<String> InputJK;
    private javax.swing.JTextField InputUsia;
    private javax.swing.JLabel LabelAktivitas;
    private javax.swing.JLabel LabelBB;
    private javax.swing.JLabel LabelJK;
    private javax.swing.JLabel LabelUsia;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
