/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo.tugas.tiga;

/**
 *
 * @author septianpadli
 */
public class OutputFrame extends javax.swing.JFrame {

    /**
     * Creates new form OutputFrame
     */
    public OutputFrame(int usia, int berat, String gender, String aktivitas, double proteinMin, double proteinMax, int karboMin, int karboMax, int serat) {
        initComponents();
        Aktivitas.setText(aktivitas);
        Berat.setText(String.valueOf(berat) + "kg");
        Gender.setText(gender);
        KarboMin.setText(String.valueOf(karboMin) + "g");
        KarboMax.setText(String.valueOf(karboMax) + "g");
        ProteinMin.setText(String.valueOf(proteinMin) + "g");
        ProteinMax.setText(String.valueOf(proteinMax) + "g");
        Serat.setText(String.valueOf(serat) + "g");
        Usia.setText(String.valueOf(usia) + " tahun");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Aktivitas = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        Berat = new javax.swing.JLabel();
        Usia = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ProteinMin = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Serat = new javax.swing.JLabel();
        separator = new javax.swing.JLabel();
        ProteinMax = new javax.swing.JLabel();
        KarboMin = new javax.swing.JLabel();
        separator1 = new javax.swing.JLabel();
        KarboMax = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Hasil Perhitungan");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Usia :");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Berat :");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Gender :");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Aktivitas :");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        Aktivitas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Aktivitas.setText("Aktivitas :");

        Gender.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Gender.setText("Gender :");

        Berat.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Berat.setText("Berat :");

        Usia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Usia.setText("Usia :");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Serat :");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Protein :");

        ProteinMin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ProteinMin.setText("Berat :");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Karbohidrat :");

        Serat.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Serat.setText("Usia :");

        separator.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        separator.setText("-");

        ProteinMax.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ProteinMax.setText("Berat :");

        KarboMin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        KarboMin.setText("Berat :");

        separator1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        separator1.setText("-");

        KarboMax.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        KarboMax.setText("Berat :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Usia)
                                    .addComponent(Berat)
                                    .addComponent(Gender)
                                    .addComponent(Aktivitas)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Serat)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ProteinMin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(separator)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ProteinMax))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(KarboMin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(separator1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(KarboMax))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1)))
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Usia)
                        .addGap(18, 18, 18)
                        .addComponent(Berat)
                        .addGap(18, 18, 18)
                        .addComponent(Gender)
                        .addGap(18, 18, 18)
                        .addComponent(Aktivitas)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(KarboMin)
                                .addComponent(separator1)
                                .addComponent(KarboMax))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Serat)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProteinMin)
                            .addComponent(separator)
                            .addComponent(ProteinMax))))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new OutputFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aktivitas;
    private javax.swing.JLabel Berat;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel KarboMax;
    private javax.swing.JLabel KarboMin;
    private javax.swing.JLabel ProteinMax;
    private javax.swing.JLabel ProteinMin;
    private javax.swing.JLabel Serat;
    private javax.swing.JLabel Usia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel separator;
    private javax.swing.JLabel separator1;
    // End of variables declaration//GEN-END:variables
}
